/* Final expense underwriting engine - browser port of the Python engine in fex/.
 *
 * This is a deliberate line-for-line port rather than a reimplementation: the
 * matching, rule evaluation, build charts and pricing all have to agree with
 * the Python side, and tests/test_parity.py runs the same cases through both
 * and compares the output. If you change behaviour here, change it there.
 *
 * Data comes from web/bundle.json, generated by tools/export_bundle.py.
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.FEX = factory();
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  // ---------------------------------------------------------------- tiers
  const TIERS = {
    preferred: { key: "preferred", rank: 0, label: "Preferred / Level Plus" },
    level: { key: "level", rank: 1, label: "Level (day-one full benefit)" },
    graded: { key: "graded", rank: 2, label: "Graded benefit" },
    modified: { key: "modified", rank: 3, label: "Modified benefit" },
    gi: { key: "gi", rank: 4, label: "Guaranteed issue" },
    decline: { key: "decline", rank: 5, label: "Decline" },
  };
  const tier = (k) => TIERS[k];
  const worstTier = (...ks) =>
    ks.reduce((a, b) => (TIERS[b].rank > TIERS[a].rank ? b : a));

  // ------------------------------------------------------------ normalize
  const NOISE = new RegExp(
    "\\b(\\d+(\\.\\d+)?\\s*(mg|mcg|ug|g|ml|iu|units?|meq|%)" +
      "|mg|mcg|ml|iu|units?|meq|tab|tabs|tablet|tablets|cap|caps|capsule|capsules" +
      "|pill|pills|dose|doses|daily|nightly|weekly|monthly|bid|tid|qid|qd|qhs|prn|po" +
      "|once|twice|three|times|a|per|day|days|week|night|morning|evening|hs|er|xr|sr|cr" +
      "|inhaler|puff|puffs|injection|shot|patch|pen|cream|drops|solution|oral)\\b",
    "gi"
  );
  const BARE_NUMBER = /\b\d+(\.\d+)?\b/g;
  const PUNCT = /[^a-z0-9+/\- ]+/g;

  function normalize(text, stripNumbers) {
    let s = (text == null ? "" : String(text)).trim().toLowerCase();
    s = s.replace(PUNCT, " ");
    s = s.replace(NOISE, " ");
    if (stripNumbers) s = s.replace(BARE_NUMBER, " ");
    return s.replace(/\s+/g, " ").trim();
  }

  // ------------------------------------------- difflib SequenceMatcher.ratio
  // Ported so fuzzy spelling matches land on the same drug as Python's
  // difflib.get_close_matches, which the Python engine uses.
  function buildB2J(b) {
    const b2j = Object.create(null);
    for (let i = 0; i < b.length; i++) {
      const ch = b[i];
      (b2j[ch] || (b2j[ch] = [])).push(i);
    }
    return b2j;
  }

  function findLongestMatch(a, b, alo, ahi, blo, bhi, b2j) {
    let besti = alo,
      bestj = blo,
      bestsize = 0;
    let j2len = Object.create(null);
    for (let i = alo; i < ahi; i++) {
      const newj2len = Object.create(null);
      const js = b2j[a[i]] || [];
      for (let n = 0; n < js.length; n++) {
        const j = js[n];
        if (j < blo) continue;
        if (j >= bhi) break;
        const k = (j2len[j - 1] || 0) + 1;
        newj2len[j] = k;
        if (k > bestsize) {
          besti = i - k + 1;
          bestj = j - k + 1;
          bestsize = k;
        }
      }
      j2len = newj2len;
    }
    return [besti, bestj, bestsize];
  }

  function matchCount(a, b) {
    const b2j = buildB2J(b);
    let total = 0;
    const queue = [[0, a.length, 0, b.length]];
    while (queue.length) {
      const [alo, ahi, blo, bhi] = queue.pop();
      const [i, j, k] = findLongestMatch(a, b, alo, ahi, blo, bhi, b2j);
      if (!k) continue;
      total += k;
      if (alo < i && blo < j) queue.push([alo, i, blo, j]);
      if (i + k < ahi && j + k < bhi) queue.push([i + k, ahi, j + k, bhi]);
    }
    return total;
  }

  function ratio(a, b) {
    const len = a.length + b.length;
    return len ? (2.0 * matchCount(a, b)) / len : 1.0;
  }

  function closestMatch(word, keys, cutoff) {
    let bestKey = null,
      bestRatio = -1;
    for (const key of keys) {
      const r = ratio(key, word);
      if (r < cutoff) continue;
      // Mirror difflib's _nlargest tie-break: highest ratio, then largest key.
      if (r > bestRatio || (r === bestRatio && bestKey !== null && key > bestKey)) {
        bestRatio = r;
        bestKey = key;
      }
    }
    return bestKey;
  }

  // ---------------------------------------------------------------- catalog
  function escapeRe(s) {
    return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }

  class Catalog {
    constructor(bundle) {
      this.conditions = new Map();
      for (const c of bundle.conditions) this.conditions.set(c.id, c);
      this.drugs = bundle.drugs;
      this.drugByIngredient = new Map();
      for (const d of this.drugs) this.drugByIngredient.set(d.ingredient, d);

      this.condIndex = new Map();
      for (const c of bundle.conditions) {
        for (const name of [c.id.replace(/_/g, " "), c.label, ...(c.aliases || [])]) {
          const key = normalize(name);
          if (key && !this.condIndex.has(key)) this.condIndex.set(key, c.id);
        }
      }
      this.drugIndex = new Map();
      for (const d of this.drugs) {
        for (const name of [d.ingredient, ...(d.brands || [])]) {
          const key = normalize(name);
          if (key && !this.drugIndex.has(key)) this.drugIndex.set(key, d);
        }
      }
    }

    _matchKey(key, index) {
      if (index.has(key)) return index.get(key);
      let best = null,
        bestLen = 0;
      for (const [alias, value] of index) {
        if (alias.length < 4) continue;
        if (new RegExp("\\b" + escapeRe(alias) + "\\b").test(key)) {
          if (alias.length > bestLen) {
            bestLen = alias.length;
            best = value;
          }
        }
      }
      if (best !== null) return best;
      const hit = closestMatch(key, index.keys(), 0.86);
      return hit === null ? null : index.get(hit);
    }

    _match(text, index) {
      for (const stripNumbers of [false, true]) {
        const key = normalize(text, stripNumbers);
        if (!key) continue;
        const hit = this._matchKey(key, index);
        if (hit != null) return hit;
      }
      return null;
    }

    matchCondition(text) {
      return this._match(text, this.condIndex);
    }
    matchDrug(text) {
      return this._match(text, this.drugIndex);
    }
    label(id) {
      const c = this.conditions.get(id);
      return c ? c.label : String(id).replace(/_/g, " ");
    }

    followupQuestion(condId, key) {
      const c = this.conditions.get(condId);
      if (!c) return null;
      const f = (c.followups || []).find((x) => x.key === key);
      return f ? f.question : null;
    }

    parseConditions(entries) {
      const parsed = [],
        unmatched = [];
      for (const entry of entries || []) {
        let name, attrs;
        if (typeof entry === "string") {
          name = entry;
          attrs = {};
        } else {
          const copy = Object.assign({}, entry);
          name = copy.name || copy.id || "";
          delete copy.name;
          delete copy.id;
          attrs = copy.attrs || copy;
          delete copy.attrs;
        }
        const id = this.conditions.has(name) ? name : this.matchCondition(String(name));
        if (!id) {
          unmatched.push(String(name));
          continue;
        }
        // When the caller passed an id (a picker selection rather than typed
        // text), show the catalog's label so generated questions read as
        // English rather than as an identifier.
        const fromPicker = String(name) === id;
        const raw = fromPicker ? this.label(id) : String(name);
        parsed.push({
          id, attrs: Object.assign({}, attrs), raw,
          inferred_from: null, verbatim: !fromPicker,
        });
      }
      return { conditions: mergeConditions(parsed), unmatched };
    }

    parseMedications(entries) {
      const meds = [],
        unmatched = [];
      for (let raw of entries || []) {
        raw = String(raw).trim();
        if (!raw) continue;
        const drug = this.matchDrug(raw);
        if (!drug) {
          meds.push({ raw, matched: false, ingredient: null, brand: null, implies: [], note: null });
          unmatched.push(raw);
          continue;
        }
        const normRaw = normalize(raw);
        const brand =
          (drug.brands || []).find((b) => normalize(b) && normRaw.includes(normalize(b))) || null;
        meds.push({
          raw,
          matched: true,
          ingredient: drug.ingredient,
          brand,
          implies: (drug.implies || []).slice(),
          note: drug.note || null,
        });
      }
      return { medications: meds, unmatched };
    }
  }

  function mergeConditions(entries) {
    const merged = new Map();
    for (const entry of entries) {
      const existing = merged.get(entry.id);
      if (!existing) {
        merged.set(entry.id, {
          id: entry.id,
          attrs: Object.assign({}, entry.attrs),
          raw: entry.raw,
          inferred_from: entry.inferred_from || null,
          verbatim: entry.verbatim !== false,
        });
        continue;
      }
      for (const [k, v] of Object.entries(entry.attrs || {})) {
        if (!(k in existing.attrs)) existing.attrs[k] = v;
      }
      if (existing.raw == null) {
        existing.raw = entry.raw;
        existing.verbatim = entry.verbatim !== false;
      }
      if (!entry.inferred_from) existing.inferred_from = null;
    }
    return Array.from(merged.values());
  }

  // ------------------------------------------------------------- predicates
  const MISSING = Symbol("missing");

  function normValue(v) {
    return typeof v === "string" ? v.trim().toLowerCase() : v;
  }

  function compare(op, actual, expected) {
    switch (op) {
      case "eq":
        return normValue(actual) === normValue(expected);
      case "ne":
        return normValue(actual) !== normValue(expected);
      case "in":
        return expected.map(normValue).includes(normValue(actual));
      case "not_in":
        return !expected.map(normValue).includes(normValue(actual));
      case "contains":
        return String(normValue(actual)).includes(String(normValue(expected)));
      case "is_true":
        return Boolean(actual) === Boolean(expected);
      case "is_false":
        return Boolean(actual) !== Boolean(expected);
      case "between":
        return Number(expected[0]) <= Number(actual) && Number(actual) <= Number(expected[1]);
      case "lt":
        return Number(actual) < Number(expected);
      case "lte":
        return Number(actual) <= Number(expected);
      case "gt":
        return Number(actual) > Number(expected);
      case "gte":
        return Number(actual) >= Number(expected);
      default:
        throw new Error("unknown operator: " + op);
    }
  }

  function evalPredicate(spec, actual) {
    const isObj = spec !== null && typeof spec === "object" && !Array.isArray(spec);
    if (isObj) {
      if ("exists" in spec) return (actual !== MISSING) === Boolean(spec.exists);
      if (actual === MISSING) return null;
      for (const [op, expected] of Object.entries(spec)) {
        if (!compare(op, actual, expected)) return false;
      }
      return true;
    }
    if (actual === MISSING) return null;
    if (Array.isArray(spec)) return compare("in", actual, spec);
    if (typeof spec === "boolean") return Boolean(actual) === spec;
    return compare("eq", actual, spec);
  }

  function evalBlock(block, facts) {
    const unknown = [];
    for (const [key, spec] of Object.entries(block || {})) {
      let actual = key in facts ? facts[key] : MISSING;
      if (actual === null || actual === undefined) actual = MISSING;
      const outcome = evalPredicate(spec, actual);
      if (outcome === false) return { result: false, unknown: [] };
      if (outcome === null) unknown.push(key);
    }
    return { result: unknown.length ? null : true, unknown };
  }

  // ------------------------------------------------------------------ rules
  function ruleTargets(rule, applicant) {
    const find = (id) => applicant.conditions.find((c) => c.id === id) || null;
    if (rule.conditions_all && rule.conditions_all.length) {
      if (!rule.conditions_all.every((id) => find(id))) return null;
      return [find(rule.conditions_all[0])];
    }
    if (rule.conditions && rule.conditions.length) {
      const matches = applicant.conditions.filter((c) => rule.conditions.includes(c.id));
      return matches.length ? matches : null;
    }
    return [null];
  }

  function describe(rule, entry) {
    if (rule.reason) return rule.reason;
    // Echo the client's own words, or the drug the condition came from; a
    // catalog label would only restate the rule.
    if (entry && entry.raw && entry.verbatim !== false) return entry.raw + ": " + rule.label;
    return rule.label;
  }

  function defaultQuestion(rule, unknown, entry) {
    const subject = entry ? entry.raw || entry.id.replace(/_/g, " ") : "the applicant";
    const pretty = unknown.map((k) => k.replace(/_/g, " ")).join(", ") || "further detail";
    return `Need ${pretty} for ${subject} to settle '${rule.label}'.`;
  }

  function evaluateRule(rule, applicant, facts) {
    const app = evalBlock(rule.applicant || {}, facts);
    if (app.result === false) return [];

    const targets = ruleTargets(rule, applicant);
    if (targets === null) return [];

    const findings = [];
    for (const entry of targets) {
      const condFacts = entry ? entry.attrs || {} : {};
      const cond = evalBlock(rule.when || {}, condFacts);
      if (cond.result === false) continue;
      const unknown = app.unknown.concat(cond.unknown);
      const onMissing = rule.on_missing || "pending";
      const isPending = unknown.length > 0 || app.result === null || cond.result === null;
      if (isPending && onMissing === "skip") continue;
      const pending = isPending && onMissing === "pending";
      const finding = {
        rule_id: rule.id,
        outcome: rule.outcome,
        reason: describe(rule, entry) + (pending ? " (unconfirmed)" : ""),
        condition_id: entry ? entry.id : null,
        pending,
        best_case: pending ? "preferred" : null,
        question: pending ? rule.question || defaultQuestion(rule, unknown, entry) : null,
        citation: rule.citation || null,
        unknown_keys: pending ? unknown.slice() : [],
        default_question: pending && !rule.question,
      };
      findings.push(finding);
    }
    return findings;
  }

  // ------------------------------------------------------------------ build
  const TIER_KEYS = [
    ["preferred_max", "level"],
    ["level_max", "graded"],
    ["graded_max", "modified"],
    ["modified_max", "gi"],
  ];

  function buildRow(chart, heightIn) {
    const keys = Object.keys(chart.rows);
    if (!keys.length) return null;
    const h = Math.round(Number(heightIn));
    if (chart.rows[String(h)]) return chart.rows[String(h)];
    let nearest = null,
      bestDelta = Infinity;
    for (const k of keys) {
      const d = Math.abs(Number(k) - h);
      if (d < bestDelta) {
        bestDelta = d;
        nearest = k;
      }
    }
    return chart.rows[nearest];
  }

  function evaluateBuild(chart, applicant) {
    if (applicant.height_in == null || applicant.weight_lb == null) {
      return [
        {
          rule_id: "build_unknown",
          outcome: "decline",
          best_case: "preferred",
          pending: true,
          reason: "Height and weight not provided (unconfirmed)",
          question: "What is the applicant's height and weight?",
          condition_id: null,
          citation: null,
        },
      ];
    }
    const row = buildRow(chart, applicant.height_in);
    if (!row) return [];
    const weight = Number(applicant.weight_lb);
    const totalIn = Math.round(Number(applicant.height_in));
    const ft = Math.floor(totalIn / 12),
      inch = totalIn % 12;
    const who = `${ft}'${inch}" ${weight.toFixed(0)} lb (BMI ${bmiOf(applicant)})`;

    if (row.min != null && weight < Number(row.min)) {
      return [
        {
          rule_id: "build_under_min",
          outcome: chart.under_min || "graded",
          reason: `Build ${who} is under the ${Number(row.min).toFixed(0)} lb minimum for this height`,
          condition_id: null,
          pending: false,
          best_case: null,
          question: null,
          citation: chart.source || null,
        },
      ];
    }

    let worstKey = null,
      outcome = null;
    for (const [key, t] of TIER_KEYS) {
      if (row[key] == null) continue;
      if (weight > Number(row[key])) {
        worstKey = key;
        outcome = t;
      }
    }
    if (outcome === null) return [];

    let highest = null,
      highestVal = -Infinity;
    for (const [key] of TIER_KEYS) {
      if (row[key] == null) continue;
      if (Number(row[key]) > highestVal) {
        highestVal = Number(row[key]);
        highest = key;
      }
    }
    const overMax = chart.over_max || "decline";
    if (worstKey === highest && TIERS[overMax].rank > TIERS[outcome].rank) outcome = overMax;

    const limit = Number(row[worstKey]);
    return [
      {
        rule_id: "build_over_" + worstKey,
        outcome,
        reason: `Build ${who} exceeds the ${limit.toFixed(0)} lb ${worstKey.replace(
          "_max",
          ""
        )} limit for this height`,
        condition_id: null,
        pending: false,
        best_case: null,
        question: null,
        citation: chart.source || null,
      },
    ];
  }

  function bmiOf(applicant) {
    if (!applicant.height_in || !applicant.weight_lb) return null;
    return Math.round((703.0 * applicant.weight_lb) / Math.pow(applicant.height_in, 2) * 10) / 10;
  }

  // ---------------------------------------------------------------- pricing
  function interpolate(curve, age) {
    const ages = Object.keys(curve)
      .map(Number)
      .sort((a, b) => a - b);
    if (age <= ages[0]) return curve[ages[0]];
    if (age >= ages[ages.length - 1]) return curve[ages[ages.length - 1]];
    for (let i = 0; i < ages.length - 1; i++) {
      const lo = ages[i],
        hi = ages[i + 1];
      if (lo <= age && age <= hi) {
        const span = hi - lo;
        const w = span ? (age - lo) / span : 0;
        return curve[lo] + (curve[hi] - curve[lo]) * w;
      }
    }
    return curve[ages[ages.length - 1]];
  }

  function illustrativeRate(pricing, applicant, tierKey, rateIndex) {
    let rate = interpolate(pricing.base_curve, applicant.age);
    rate *= pricing.gender_factor[applicant.gender] != null ? pricing.gender_factor[applicant.gender] : 1.0;
    if (applicant.tobacco) rate *= pricing.tobacco_factor;
    rate *= pricing.tier_factor[tierKey] != null ? pricing.tier_factor[tierKey] : 1.0;
    rate *= rateIndex == null ? 1.0 : rateIndex;
    return rate;
  }

  function lookupTable(table, applicant, tierKey) {
    const byGender = table.rates[tierKey];
    if (!byGender) return null;
    const byTobacco = byGender[applicant.gender] || byGender.unisex;
    if (!byTobacco) return null;
    const curve = byTobacco[applicant.tobacco ? "tobacco" : "nontobacco"];
    if (!curve) return null;
    return interpolate(curve, applicant.age);
  }

  function quote(bundle, applicant, carrier, product, tierKey) {
    const face = Math.max(product.face_min, Math.min(product.face_max, applicant.face_amount));
    const table = bundle.rate_tables ? bundle.rate_tables[carrier.id] : null;
    let rate = table ? lookupTable(table, applicant, tierKey) : null;
    let fee, monthlyFactor, illustrative, basis;
    if (rate != null) {
      fee = table.policy_fee_annual;
      monthlyFactor = table.monthly_factor;
      illustrative = table.illustrative;
      basis = table.source || carrier.name + " rate table";
    } else {
      rate = illustrativeRate(bundle.pricing, applicant, tierKey, carrier.rate_index);
      fee = bundle.pricing.policy_fee_annual;
      monthlyFactor = bundle.pricing.monthly_factor;
      illustrative = true;
      basis = "Illustrative model - not a carrier rate table";
    }
    const annual = rate * (face / 1000.0) + fee;
    return {
      monthly: annual * monthlyFactor,
      annual,
      face_amount: face,
      rate_per_1000_annual: rate,
      policy_fee_annual: fee,
      illustrative,
      basis,
    };
  }

  // ----------------------------------------------------------------- engine
  class Engine {
    constructor(bundle) {
      this.bundle = bundle;
      this.catalog = new Catalog(bundle);
      this.carriers = bundle.carriers;
    }

    inferFromMedications(meds) {
      const inferred = [],
        questions = [];
      for (const med of meds) {
        if (!med.matched || !med.ingredient) continue;
        const drug = this.catalog.drugByIngredient.get(med.ingredient);
        if (!drug) continue;
        const label = med.brand || drug.ingredient;

        if (drug.confidence === "low") {
          if ((drug.implies && drug.implies.length) || drug.note) {
            const candidates = (drug.implies || []).map((c) => this.catalog.label(c)).join(", ");
            const detail = drug.note || "";
            const tail = candidates ? ` Possible: ${candidates}.` : "";
            questions.push(`${label}: what is it being taken for? ${detail}${tail}`.trim());
          }
          continue;
        }
        for (const condId of drug.implies || []) {
          inferred.push({
            id: condId,
            attrs: Object.assign({}, (drug.set || {})[condId] || {}),
            raw: `${label} (from medication)`,
            inferred_from: label,
            verbatim: true,
          });
        }
        for (const flag of drug.flags || []) {
          inferred.push({
            id: flag,
            attrs: {},
            raw: `${label} (from medication)`,
            inferred_from: label,
            verbatim: true,
          });
        }
        if (drug.confidence === "medium" && drug.note) questions.push(`${label}: ${drug.note}`);
      }
      return { inferred: mergeConditions(inferred), questions };
    }

    buildApplicant(input) {
      const parsed = this.catalog.parseConditions(input.conditions || []);
      const meds = this.catalog.parseMedications(input.medications || []);
      const inf = this.inferFromMedications(meds.medications);

      let gender = (input.gender || "male").trim().toLowerCase();
      if (gender === "m" || gender === "man") gender = "male";
      else if (gender === "f" || gender === "woman") gender = "female";

      const applicant = {
        age: input.age,
        gender,
        tobacco: Boolean(input.tobacco),
        state: input.state || null,
        height_in: input.height_in == null ? null : Number(input.height_in),
        weight_lb: input.weight_lb == null ? null : Number(input.weight_lb),
        face_amount: input.face_amount == null ? 10000 : Number(input.face_amount),
        conditions: mergeConditions(parsed.conditions.concat(inf.inferred)),
        medications: meds.medications,
      };
      applicant.bmi = bmiOf(applicant);
      return {
        applicant,
        unmatchedConditions: parsed.unmatched,
        unmatchedMedications: meds.unmatched,
        questions: inf.questions,
      };
    }

    facts(applicant) {
      return {
        age: applicant.age,
        gender: applicant.gender,
        tobacco: applicant.tobacco,
        state: applicant.state,
        height_in: applicant.height_in,
        weight_lb: applicant.weight_lb,
        bmi: applicant.bmi,
        face_amount: applicant.face_amount,
        condition_count: applicant.conditions.length,
        medication_count: applicant.medications.length,
      };
    }

    /* Replace fallback question wording with the catalog's own follow-up, so
     * two carriers needing the same fact ask one readable question instead of
     * two rule-flavoured ones. Mirrors Engine._improve_questions in Python. */
    improveQuestions(findings) {
      for (const f of findings) {
        if (!(f.pending && f.default_question && f.condition_id)) continue;
        const asks = (f.unknown_keys || []).map((k) =>
          this.catalog.followupQuestion(f.condition_id, k)
        );
        if (asks.length && asks.every(Boolean)) {
          f.question = Array.from(new Set(asks)).join(" ");
        }
      }
    }

    selectProduct(carrier, tierKey, applicant) {
      const candidates = carrier.products.filter(
        (p) =>
          p.issue_age_min <= applicant.age &&
          applicant.age <= p.issue_age_max &&
          (!applicant.state || !(p.states_excluded || []).includes(applicant.state.toUpperCase())) &&
          (p.bypass_underwriting || TIERS[p.tier].rank >= TIERS[tierKey].rank)
      );
      if (!candidates.length) return null;
      return candidates.reduce((a, b) => (TIERS[b.tier].rank < TIERS[a.tier].rank ? b : a));
    }

    evaluateCarrier(applicant, carrier) {
      if (
        applicant.state &&
        (carrier.states_excluded || []).includes(applicant.state.toUpperCase())
      ) {
        return null;
      }
      const facts = this.facts(applicant);
      let findings = [];
      for (const rule of carrier.rules) {
        findings = findings.concat(evaluateRule(rule, applicant, facts));
      }
      if (carrier.build) findings = findings.concat(evaluateBuild(carrier.build, applicant));

      this.improveQuestions(findings);
      const settled = findings.filter((f) => !f.pending);
      const pending = findings.filter((f) => f.pending);

      const bestTierOfCarrier = carrier.products.reduce(
        (a, p) => (TIERS[p.tier].rank < TIERS[a].rank ? p.tier : a),
        "decline"
      );
      let tierKey = settled.length
        ? worstTier(bestTierOfCarrier, ...settled.map((f) => f.outcome))
        : bestTierOfCarrier;
      let worstCase = pending.length
        ? worstTier(tierKey, ...pending.map((f) => f.outcome))
        : tierKey;

      const product = this.selectProduct(carrier, worstCase, applicant);
      const bestProduct = this.selectProduct(carrier, tierKey, applicant);

      const sorted = findings
        .slice()
        .sort((a, b) => TIERS[b.outcome].rank - TIERS[a.outcome].rank);
      const openQuestions = pending.map((f) => f.question).filter(Boolean);

      if (!product && !bestProduct) {
        const reasons = sorted.slice();
        if (!findings.some((f) => f.outcome === "decline")) {
          const inAge = carrier.products.some(
            (p) => p.issue_age_min <= applicant.age && applicant.age <= p.issue_age_max
          );
          reasons.push({
            rule_id: "no_product",
            outcome: "decline",
            reason: inAge
              ? "This carrier has no plan that issues at the required benefit tier"
              : `No product available at issue age ${applicant.age}`,
            condition_id: null,
            pending: false,
            best_case: null,
            question: null,
            citation: null,
          });
        }
        return {
          carrier_id: carrier.id,
          carrier_name: carrier.name,
          product_id: "",
          product_name: "No offer",
          tier: "decline",
          best_case_tier: "decline",
          certain: true,
          eligible: false,
          findings: reasons,
          blocking_reasons: reasons.filter((f) => f.outcome === "decline").map((f) => f.reason),
          open_questions: openQuestions,
          notes: (carrier.notes || []).slice(),
          quote: null,
          benefit_schedule: null,
          am_best: carrier.am_best,
        };
      }

      const chosen = product || bestProduct;
      let chosenTier = chosen.bypass_underwriting
        ? chosen.tier
        : worstTier(worstCase, chosen.tier);
      const upside = bestProduct || chosen;
      const bestCaseTier = upside.bypass_underwriting ? upside.tier : worstTier(tierKey, upside.tier);

      const priced = quote(this.bundle, applicant, carrier, chosen, chosenTier);

      const notes = (carrier.notes || []).concat(chosen.notes || []);
      if (!carrier.verified) {
        notes.push(
          "Guidelines are unverified defaults - confirm against the carrier's current field underwriting guide."
        );
      }
      const face = Math.max(chosen.face_min, Math.min(chosen.face_max, applicant.face_amount));
      if (face !== applicant.face_amount) {
        notes.push(
          `Face amount adjusted to $${face.toLocaleString()} to fit this product's $${chosen.face_min.toLocaleString()}-$${chosen.face_max.toLocaleString()} range.`
        );
      }

      return {
        carrier_id: carrier.id,
        carrier_name: carrier.name,
        product_id: chosen.id,
        product_name: chosen.name,
        tier: chosenTier,
        best_case_tier: bestCaseTier,
        certain: chosenTier === bestCaseTier,
        eligible: chosenTier !== "decline",
        findings: sorted,
        blocking_reasons: sorted.filter((f) => f.outcome === chosenTier).map((f) => f.reason),
        open_questions: openQuestions,
        notes,
        quote: priced,
        benefit_schedule: chosen.benefit_schedule,
        face_min: chosen.face_min,
        face_max: chosen.face_max,
        am_best: carrier.am_best,
      };
    }

    evaluate(applicant, extraQuestions) {
      const results = [];
      for (const carrier of this.carriers) {
        const result = this.evaluateCarrier(applicant, carrier);
        if (result) results.push(result);
      }
      results.sort((a, b) => {
        const d1 = TIERS[a.best_case_tier].rank - TIERS[b.best_case_tier].rank;
        if (d1) return d1;
        const d2 = TIERS[a.tier].rank - TIERS[b.tier].rank;
        if (d2) return d2;
        return (a.quote ? a.quote.monthly : 1e9) - (b.quote ? b.quote.monthly : 1e9);
      });

      const questions = (extraQuestions || []).slice();
      for (const result of results) {
        for (const q of result.open_questions) if (!questions.includes(q)) questions.push(q);
      }

      const warnings = [];
      if (applicant.height_in == null || applicant.weight_lb == null) {
        warnings.push(
          "No height/weight entered - build is one of the most common reasons a level case comes back graded, so every carrier is showing its worst case."
        );
      }
      if (applicant.medications.some((m) => m.matched === false)) {
        warnings.push(
          "Some medications were not recognised. Check the spelling, or enter the condition directly."
        );
      }
      return { applicant, results, open_questions: questions, warnings };
    }

    run(input) {
      const built = this.buildApplicant(input);
      const report = this.evaluate(built.applicant, built.questions);
      report.unmatched_medications = built.unmatchedMedications;
      report.unmatched_conditions = built.unmatchedConditions;
      if (built.unmatchedConditions.length) {
        report.warnings.push(
          "Not recognised as conditions: " + built.unmatchedConditions.join(", ")
        );
      }
      return report;
    }
  }

  return { Engine, Catalog, TIERS, normalize, ratio, mergeConditions, bmiOf, quote };
});
